### ISSUE TITLE
Not working in Xcode 8

### ISSUE THREAD

**Issue by artemnovichkov** [zntfdr/Christmas-Xcode-Color-Theme#1]
I'm using Xcode 8.2 (8C38), but I can't install this theme. Have tried .dvtcolortheme and .xccolortheme extension.

**Comment by artemnovichkov** [comment]
@zntfdr checked on two Macbooks, new theme appears in `Font and Colors`, but looks like `Default` theme.

**Comment by zntfdr** [comment]
Yay!

![leonardo-dicaprio-celebrate-gif_thum](https://cloud.githubusercontent.com/assets/5277837/21353276/e1566750-c6f7-11e6-8e00-0a15884214e7.gif)

🎄  Merry Christmas to you too 🤗
